### ISSUE TITLE
Unable to use `geometry-zsh/geometry` as a prompt without errors

### ISSUE THREAD

**Issue by naphta** [marlonrichert/zsh-snap#67]
Not sure if this is one for them or you but when using geometry with snap I get some errors on second start, which to me look like it's trying to source .zwc files, but I'm not particularly familiar with the inner workings (magic) of zsh.

I've attached the output I get on startup, and the zshrc which generated it. Happy to do any digging and playing but the configuration is fairly basic.

[znap-output.txt](https://github.com/marlonrichert/zsh-snap/files/6364723/znap-output.txt)
[zshrc.txt](https://github.com/marlonrichert/zsh-snap/files/6364778/zshrc.txt)

**Comment by marlonrichert** [comment]
The problem is with them: Just do `source ~[geometry]/geometry.zsh` and you'll see the exact same error output.

The bug is here: https://github.com/geometry-zsh/geometry/blob/a8033e0e9a987c1a6ee1813b7cad7f28cfd3c869/geometry.zsh#L17
```zsh
function { local fun; for fun ("${GEOMETRY[ROOT]}"/functions/*) . $fun }
```

Znap auto-compiles all of the files in `~[geometry]/functions/`. So, for each source file in that dir, it will create a `.zwc` file in the same dir. The anonymous function above then tries to source each file in the dir, _including all `.zwc` files._ That doesn't work.

**Comment by naphta** [comment]
> The problem is with them: Just do `source ~[geometry]/geometry.zsh` and you'll see the exact same error output.
> 
> The bug is here: https://github.com/geometry-zsh/geometry/blob/a8033e0e9a987c1a6ee1813b7cad7f28cfd3c869/geometry.zsh#L17
> 
> ```shell
> function { local fun; for fun ("${GEOMETRY[ROOT]}"/functions/*) . $fun }
> ```
> 
> Znap auto-compiles all of the files in `~[geometry]/functions/`. So, for each source file in that dir, it will create a `.zwc` file in the same dir. The anonymous function above then tries to source each file in the dir, _including all `.zwc` files._ That doesn't work.

Many thanks for looking. I had a feeling it was something like that, I caused the same bug in my dotfiles not too long ago.
