### ISSUE TITLE
lazy evaluation? benchmarks? updates

### ISSUE THREAD

**Issue by xenoterracide** [marlonrichert/zsh-snap#94]
Does zsnap do any lazy evalution? such as I don't want to do any evaluation until conditions such as prompt available or command pattern matched for completion?

do you have any comparison times with other frameworks?

how does zsnap update plugins and itself? do I need to write a cron/timer?

**Comment by marlonrichert** [comment]
That’s a lot of questions for one issue. 😉

**Comment by marlonrichert** [comment]
> Does zsnap do any lazy evalution? such as I don't want to do any evaluation until conditions such as prompt available or command pattern matched for completion?

Can you give some concrete examples of how you would want to use this and why?

**Comment by marlonrichert** [comment]
> do you have any comparison times with other frameworks?

I don’t. What would be a meaningful comparison to you?

**Comment by marlonrichert** [comment]
> how does zsnap update plugins and itself? 

`znap status` checks for updates to Znap and of your (plugin) repos in parallel.

`znap pull` without arguments will update Znap and all repos, or you can pass as arguments the specific repos you want to update. 

> do I need to write a cron/timer?

I have not yet implemented an auto-update feature, because I personally don’t want that. But I am now considering perhaps to implement a selective auto-update mechanism.
